# Generated by Django 5.2.8 on 2026-01-03 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_options_alter_application_status'),
        ('jobs', '0003_savedjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='unique_application_per_user_job'),
        ),
    ]
