# Generated by Django 5.2.8 on 2026-01-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
