# Generated by Django 5.2.8 on 2026-01-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
